development:
  adapter: postgresql
  encoding: unicode
  database: d13iqoi43a8ksg
  pool: 5
  host: ec2-54-225-115-77.compute-1.amazonaws.com
  username: acpprhmybettwj
  password: y18wRPwlfNgUvMcMPtPEoksL6i

test:
  adapter: postgresql
  encoding: unicode
  database: listnepal-test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: listnepal-prod
  pool: 5
  host: localhost
  username: action
  password: